language: php

php:
  - 7
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

env:
  - LARAVEL_VERSION="~5.5" TESTBENCH_VERSION="~3.5"

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit

matrix:
  allow_failures:
  - php: 7.2
